package com.example.backend.ai.tools;

public enum AiTool {
    GET_MONTH_REVENUE,
    GET_REVENUE_TREND,
    GET_UNPAID_INVOICES,
    GET_OVERDUE_INVOICES,
    GET_TASK_LOAD_PER_EMPLOYEE,
    PREDICT_REVENUE,
    PREDICT_CASH_FLOW,
    CALCULATE_PAYMENT_RISK,
    GET_APPOINTMENT_SUMMARY,
    GET_SUPPLIER_ANALYTICS,

    GET_CLIENT_LIST,
    GET_CLIENT_COUNT,
    GET_CLIENT_ANALYTICS,
    GET_CLIENT_REVENUE_SUMMARY,

    GET_EMPLOYEE_LIST,
    GET_EMPLOYEE_DETAILS,
    GET_EMPLOYEE_PERFORMANCE,
    GET_EMPLOYEE_TASK_HISTORY,

    GET_FACTURE_LIST,
    GET_FACTURE_DETAILS,
    GET_INVOICE_STATISTICS,

    GET_YEARLY_REVENUE,
    GET_REVENUE_BY_CLIENT,
    GET_EXPENSE_SUMMARY,
    GET_PROFIT_ANALYSIS,
    GET_MONTHLY_PROFIT,

    GET_TASK_STATISTICS,
    GET_COMPLETED_TASKS,
    GET_OVERDUE_TASKS,
    GET_TASK_BY_DATE_RANGE,

    GET_GLOBAL_KPIS,
    GET_ENTERPRISE_OVERVIEW
}
